FROM fedora:42

RUN dnf install -y \
    gcc-c++ \
    cmake \
    make \
    gtest-devel \
    && dnf clean all

WORKDIR /src

COPY CMakeLists.txt .
COPY include/ include/
COPY test/ test/

CMD ["bash", "-c", "cmake -B build -DPIPEPP_CORE_BUILD_TESTS=ON -DCMAKE_CXX_FLAGS='-std=c++20 -fno-rtti -fno-exceptions' && cmake --build build --parallel && cd build && ctest --output-on-failure"]